version: "3.8"
services:
  mongodb:
    image : mongo
    container_name: mongo-db
    environment:
      - PUID=1000
      - PGID=1000
      - MONGO_INITDB_ROOT_PASSWORD=changeMe123
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
